### PR TITLE
Resolve #80 - Ignore missing json files when selectively running tests

### LINKED ISSUE #80: Ignore missing json files when selectively running tests
I have a bunch of tests that create json files. It is often useful to just run one or two tests/scenarios:

mvn clean verify -Dtest=LoginTest,AccountsTest

The report is configured to parse multiple files:

<jsonFiles>
  <param>${project.build.directory}/json-report/Login.json</param>
  <param>${project.build.directory}/json-report/Accounts.json</param>
  <param>${project.build.directory}/json-report/AccountSources.json</param>
....

The AccountSources.json is not generated, and so the report fails with a java.io.FileNotFoundException.

The report should not fail on missing files, rather only warn.

### PR DESCRIPTION
**Pull request by AndyGee**

### CODE REVIEW

**Comment by AndyGee** [comment]
Tested against https://github.com/damianszczepanik/cucumber-reporting/pull/693

**Comment by damianszczepanik** [comment]
Looks like good candidate but probably for https://github.com/damianszczepanik/cucumber-reporting project

**Comment by AndyGee** [comment]
If the report gets missing files it will fail, so the idea here is: only send files if the mojo finds them, and also not to fail (warn) when nothing is found.

**Comment by damianszczepanik** [comment]
If you move the logic into project I mentioned then this code can be shared across 3 other projects. If the logic is here it won't be easy to apply same feature for other projects.

So my idea is to pass from this project control what to do (via `Configuration` class) but the logic what to do should be in cucumber-reporting project.

**Comment by AndyGee** [comment]
Ok, I'll look into it.

**Comment by damianszczepanik** [comment]
@AndyGee as this helps with #80 - are you planing to complete this PR?

**Pull request closed without merging**
